# Generated by Django 3.0.5 on 2020-04-19 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carmake_name', models.CharField(max_length=50)),
                ('carmake_value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carmodel_name', models.CharField(max_length=50)),
                ('carmodel_value', models.CharField(max_length=50)),
                ('carmake_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoscrape.CarMake')),
            ],
        ),
        migrations.CreateModel(
            name='CarTrim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartrim_name', models.CharField(max_length=50)),
                ('cartrim_value', models.CharField(max_length=50)),
                ('carmake_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoscrape.CarMake')),
                ('carmodel_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoscrape.CarModel')),
            ],
        ),
        migrations.CreateModel(
            name='CarResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('miles', models.IntegerField()),
                ('price', models.FloatField()),
                ('carmake_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoscrape.CarMake')),
                ('carmodel_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoscrape.CarModel')),
                ('cartrim_pk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoscrape.CarTrim')),
            ],
        ),
    ]
