# Generated by Django 3.0.5 on 2020-04-19 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoscrape', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='carmake_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='autoscrape.CarMake'),
        ),
        migrations.AlterField(
            model_name='cartrim',
            name='carmake_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trims', to='autoscrape.CarMake'),
        ),
        migrations.AlterField(
            model_name='cartrim',
            name='carmodel_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trims', to='autoscrape.CarModel'),
        ),
    ]
