# Generated by Django 3.0.5 on 2020-04-20 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoscrape', '0002_auto_20200419_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carresult',
            name='carmake_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='autoscrape.CarMake'),
        ),
        migrations.AlterField(
            model_name='carresult',
            name='carmodel_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='autoscrape.CarModel'),
        ),
        migrations.AlterField(
            model_name='carresult',
            name='cartrim_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='autoscrape.CarTrim'),
        ),
    ]
