# Generated by Django 3.0.5 on 2020-04-21 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoscrape', '0003_auto_20200420_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmake',
            old_name='carmake_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='carmake',
            old_name='carmake_value',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='carmodel_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='carmodel_value',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='cartrim',
            old_name='cartrim_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cartrim',
            old_name='cartrim_value',
            new_name='value',
        ),
    ]
